openapi: 3.0.1
info:
  title: Test API
  version: 1.0.0

paths:
  /depth9:
    get:
      summary: Get data with nested objects
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Level9'
components:
  schemas:
    Level9:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Level8'
        level8:
          $ref: '#/components/schemas/Level8'
    Level8:
      type: object
      properties:
        data:
          type: string
        level7:
          $ref: '#/components/schemas/Level7'
    Level7:
      type: object
      properties:
        data:
          type: string
        level6:
          $ref: '#/components/schemas/Level6'
    Level6:
      type: object
      properties:
        data:
          type: string
        level5:
          $ref: '#/components/schemas/Level5'
    Level5:
      type: object
      properties:
        data:
          type: string
        level4:
          $ref: '#/components/schemas/Level4'
    Level4:
      type: object
      properties:
        data:
          type: string
        level3:
          $ref: '#/components/schemas/Level3'
    Level3:
      type: object
      properties:
        data:
          type: string
        level2:
          $ref: '#/components/schemas/Level2'
    Level2:
      type: object
      properties:
        data:
          type: string
        level1:
          $ref: '#/components/schemas/Level1'
    Level1:
      type: object
      properties:
        data:
          type: string