openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /enum-array:
    get:
      parameters:
        - in: query
          name: sort
          schema:
            type: string
            enum: [asc, desc]
  /enum-list:
    get:
      parameters:
        - in: query
          name: sort
          description: Sort order
          schema:
            type: string
            enum:
              - asc
              - desc
      responses:
        '200':
          description: OK
  /enum-with-description:
    get:
      parameters:
        - in: query
          name: sort
          schema:
            type: string
            enum: [ asc, desc ]
          description: >
            Sort order:
             * `asc` - Ascending, from A to Z
             * `desc` - Descending, from Z to A
      responses:
        '200':
          description: OK
  /enum-nullable:
    get:
      parameters:
        - in: query
          name: sort
          description: Sort order
          schema:
            type: string
            nullable: true  # <---
            enum:
              - asc
              - desc
              - null        # <--- without quotes, i.e. null not "null"
      responses:
        '200':
          description: OK
  /enum-reusable:
    get:
      parameters:
        - in: query
          name: color
          required: true
          schema:
            $ref: '#/components/schemas/Color'
      responses:
        '200':
          description: OK
components:
  schemas:
    Color:
      type: string
      enum:
        - black
        - white
        - red
        - green
        - blue