openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /pet/findByStatus:
    get:
      summary: Finds pets by Status
      tags:
        - pets
  /pet:
    post:
      summary: Adds a new pet to the store
      tags:
        - pets
  /store/single:
    get:
      summary: Returns single pet
      tags:
        - single
  /store/inventory:
    put:
      summary: Returns pet inventories
      tags:
        - store
  /krama:
    post:
      summary: Returns pet krama
      tags:
        - krama
  /magaz:
    get:
      summary: Returns pet magaz
      tags:
        - magaz
        - store
  /supermarket:
    get:
      summary: Returns pet supermarket
      tags:
        - magaz
        - krama
  /cat:
    post:
      summary: Adds a new cat
      tags: [cat]
  /dog:
    post:
      summary: Adds a new dog
      tags: [dog]
  /dog/bark:
    put:
      summary: Adds a new pet who bark
      tags: [dog, pet]
  /dog-pet:
    put:
      summary: Adds a new pet who dog
      tags: [dog, pet]
  /dog-man-friendly:
    get:
      summary: Adds a new man to dog
      tags: [ man ]
  /no-tag:
    get:
      summary: No tag