name: Build documentation

on:
  # If specified, the workflow will be triggered automatically once you push to the `main` branch.
  # Replace `main` with your branch’s name
  push:
    branches: ["main"]
  # Specify to run a workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Gives the workflow permissions to clone the repo and create a page deployment
permissions:
  id-token: write
  pages: write

env:
  # Name of module and id separated by a slash
  INSTANCE: Writerside2/auto
  # Replace HI with the ID of the instance in capital letters
  ARTIFACT: webHelpAUTO2-all.zip
  # Writerside docker image version
  DOCKER_VERSION: '241.18775'
  # Add the variable below to upload Algolia indexes
  # Replace HI with the ID of the instance in capital letters
  ALGOLIA_ARTIFACT: 'algolia-indexes-AUTO.zip'
  ALGOLIA_APP_NAME: 'ERUSDW4898'
  ALGOLIA_INDEX_NAME: 'index_test'
  ALGOLIA_KEY: '${{ secrets.ALGOLIA_KEY }}'
  CONFIG_JSON_PRODUCT: 'AUTO'
  CONFIG_JSON_VERSION: '1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.jetbrains.team/p/writerside/builder/writerside-builder:2.1.1954-p6706

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Processing timestamps
#        run: |
#          git config --global --add safe.directory /__w/siarb.github.io/siarb.github.io
#          mkdir -p ./timestamps
#          echo "{" > ./timestamps/timestamps.json
#          git ls-tree -r --name-only HEAD | grep -E '\.(topic|md)$' | xargs -n 1 -P 4 -I{} bash -c 'echo -e "\"$0\": \"$(git log -1 --format="%at" -- "$0")\","' {} >> ./timestamps/timestamps.json
#          sed -i '$ s/.$//' ./timestamps/timestamps.json
#          echo "}" >> ./timestamps/timestamps.json
#          cat ./timestamps/timestamps.json
#
#      - name: Store timestamps file
#        uses: actions/upload-artifact@v4
#        with:
#          name: timestamps.json
#          path: ./timestamps/timestamps.json
#
#      - name: Download timestamps
#        uses: actions/download-artifact@v4
#        with:
#          name: timestamps.json
#          path: timestamps

      - name: Build Writerside docs using Docker
        run: |
          set -x
          echo $GITHUB_WORKSPACE/Writerside2/images/book.jpg
          pwd
          echo "Build documentation script started"
          export DISPLAY=:99
          Xvfb :99 &
          git config --global --add safe.directory .
          /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product ${{ env.INSTANCE }} --runner github -output-dir ./artifacts -pdf PDF.xml || true
      #          echo "Test existing artifacts"
      #          test -e ./artifacts/${{ env.ARTIFACT }} && echo ${{ env.ARTIFACT }} exists
#        uses: JetBrains/writerside-github-action@v4
#        with:
#          instance: ${{ env.INSTANCE }}
#          artifact: ${{ env.ARTIFACT }}
#          docker-version: ${{ env.DOCKER_VERSION }}

      - name: List artifacts directory
        run: |
          ls -alR ./artifacts

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/pdfSourceAUTO.pdf
            artifacts/cover.pdf
            artifacts/pdfSourceAUTO.html
          retention-days: 7
