name: Build docs

on:
  push:
    branches: ["main"]

  workflow_dispatch:

env:
  PRODUCT: name_of_module/instance_id
  ARTIFACT: webHelpXX2-all.zip
  DOCKER_VERSION: '2.1.1430-p3709'


jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Docker version
        id: docker
        run: echo "DOCKER_VERSION=${{ env.DOCKER_VERSION }}" >> $GITHUB_ENV
      - name: Build Writerside docs using Docker
        uses: siarb/writerside-docker-action@v1.104
        with:
          DOCKER_VERSION: ${{ env.DOCKER_VERSION }}
      - name: Get DOCKER_VERSION
        run: echo "DOCKER_VERSION was ${{ steps.docker.outputs.DOCKER_VERSION }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifacts/${{ env.ARTIFACT }}
          retention-days: 7

