name: Build docs

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  PRODUCT: Writerside/m
  DOC_ARTIFACT: webHelpM2-all.zip
  DOCKER_IMAGE: registry.jetbrains.team/p/writerside/builder/writerside-builder:2.1.1463-p3799

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Docker build args
        run: echo "DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}" >> $GITHUB_ENV

      - name: Build docs with Docker
        uses: siarb/writerside-docker-action@v1.92
        with:
          DOCKER: ${{ env.DOCKER_IMAGE }}
          DOCKERFILE: <Dockerfile-path>
          ENTRYPOINT: entrypoint.sh

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: help
          path: ${env.DOC_ARTIFACT}
          retention-days: 7
