name: Build docs

on:
  push:
    branches: ["main"]

  workflow_dispatch:

env:
  INSTANCE: Writerside/m
  ARTIFACT: webHelpM2-all.zip
  TAG: '2.1.1471-p3848'


jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Writerside docs using Docker
        uses: siarb/writerside-docker-action@v1.153
        env:
          TAG: ${{ env.TAG }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifacts/${{ env.ARTIFACT }}
          retention-days: 7

