on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: 'Siarhei'
      # Use the output from the `hello` step
      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v1